In [1]:
#Install
pip install numpy
"""
What and why? Numpy is a library used to manipulate arrays. Its is 50x faster than pythons lists. Used for data scientic where speed is important
"""

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 12.7 MB/s  0:00:01m0:00:0100:01

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
"""Dimensions in Arrays"""
#0-D array(scalar)
zero = np.array(42)
print(zero)

#1-D Arrays
one = np.array([1,2,3,4,5])
print(one)

#2-D
two = np.array([[1,2,3], [4,5,6]])
print(two)

"""Checking Number of dimensions"""
print(zero.ndim)
print(one.ndim)
print(two.ndim)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
0
1
2


In [7]:
""" Creating higher dimension arrays """
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("number of dimensions: ", arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions:  5


In [9]:
"""NumPy array indexing"""
arr = np.array([1,2,3,4,5])
print(arr[0])

arr = np.array([[[]]])

#use negative indexs to access values from the back

1


In [18]:
"""NumPy Slicing """
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])

#negative slicing: slices from the end
print(arr[-3:-1])

#Step: use step
print(arr[1:5:2])

#Slicing 2-D array:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[7 8 9]


In [19]:
"""
NumPy Data Types:
i - int
b - bool
f - float
c - complex float
m - timedelta
M - datetime
O - object
ect.
"""

'\nNumPy Data Types:\ni - int\nb - bool\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nect.\n'

In [26]:
"""Shape is the number of elements in each diemnsion """
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

"""reshaping allows you to change the number of dimensons and allows you to change the number of elements in each dimension"""
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newArr = arr.reshape(3,4)
print("reshape ex1:",newArr)

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newArr = arr.reshape(2,3,2)
print("reshape ex2:", newArr)
"""you can use reshape to flatten an n-dimension array into a 1-D array"""
print("flatten: ",newArr.reshape(-1))

(2, 5)
reshape ex1: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape ex2: [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
flatten:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
