In [1]:
#Install
pip install numpy
"""
What and why? Numpy is a library used to manipulate arrays. Its is 50x faster than pythons lists. Used for data scientic where speed is important
"""

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 12.7 MB/s  0:00:01m0:00:0100:01

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
"""Dimensions in Arrays"""
#0-D array(scalar)
zero = np.array(42)
print(zero)

#1-D Arrays
one = np.array([1,2,3,4,5])
print(one)

#2-D
two = np.array([[1,2,3], [4,5,6]])
print(two)

"""Checking Number of dimensions"""
print(zero.ndim)
print(one.ndim)
print(two.ndim)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
0
1
2


In [7]:
""" Creating higher dimension arrays """
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("number of dimensions: ", arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions:  5


In [29]:
"""NumPy array indexing"""
arr = np.array([1,2,3,4,5])
print(arr[0])

#Access the third element of the second array of the first array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

#use negative indexs to access values from the back
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

1
6
Last element from 2nd dim:  10


In [18]:
"""NumPy Slicing """
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])

#negative slicing: slices from the end
print("negative slicing: ",arr[-3:-1])

#Step: use step value to deetermine the step of slicing:
print("Using step value: ",arr[1:5:2])

#Slicing 2-D array:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2-D slicing: ",arr[1, 1:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[7 8 9]


In [19]:
"""
NumPy Data Types:
i - int
b - bool
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chun of memory for other type(void)
"""

'\nNumPy Data Types:\ni - int\nb - bool\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nect.\n'

In [53]:
"""Shape is the number of elements in each diemnsion """
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

"""reshaping allows you to change the number of dimensons and allows you to change the number of elements in each dimension"""
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newArr = arr.reshape(3,4)
print("reshape ex1:\n",newArr)

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newArr = arr.reshape(2,3,2)
print("reshape ex2:\n", newArr)
"""you can use reshape to flatten an n-dimension array into a 1-D array"""
print("flatten:",newArr.reshape(-1))

(2, 5)
reshape ex1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape ex2:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [36]:
"""NumPy Array Iterating"""
#1-D itertion
print("1-D")
arr = np.array([1, 2, 3])
for x in arr:
  print(x)
    
#3-D iteratrion
print("3-D")
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

#iteration using nditer()
print("3-D using nditer()")
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

#using nditer() and step value to skipping every other value
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("2-D using nditer() skipping every other using step")
for x in np.nditer(arr[:, ::2]):
  print(x)

1-D
1
2
3
3-D
1
2
3
4
5
6
7
8
9
10
11
12
3-D using nditer()
1
2
3
4
5
6
7
8
2-D using nditer() skipping every other
1
3
5
7


In [52]:
"""NumPy Joining Array: Joining menas putting contents fo two or more arrays in a single array """\
#Joining 1-D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print("Joining 1-D arrays:", arr)

#Joining 2-D arrays(denote axis)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print("Joining 2-D arrays with axis=1:\n",arr)

Joining 1-D arrays: [1 2 3 4 5 6]
Joining 2-D arrays with axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


In [59]:
"""Joininig using stack: Stacking is the same as concatention, the only difference is that stacking is done along a new axis """
#Stacking
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print("Stacking with axis=1:\n",arr)
arr = np.stack((arr1, arr2), axis=0)
print("Stacking with axis=0:\n",arr)

#Stacking along rows using hstack()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print("Row stacking:",arr)

#Stacking along columns using vstack()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print("Column stacking:\n",arr)

Stacking with axis=1:
 [[1 4]
 [2 5]
 [3 6]]
Stacking with axis=0:
 [[1 2 3]
 [4 5 6]]
Row stacking [1 2 3 4 5 6]
Column stacking
 [[1 2 3]
 [4 5 6]]


In [62]:
"""NumPy Splitting Array: We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits"""
#splitting 1-D Array into n parts
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

#You can also split using hsplit() and vsplit()!

[array([1, 2]), array([3, 4]), array([5, 6])]


In [69]:
"""NumPy: Searching arrays"""
#Searchin with where()
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print("Where is 4:",x)

#searching with searchsorted(): it preforms a binary search in the array and returns the index where a specified value qould be inserted
#to maintain the seearch order. NOTE: ASSUMES THE ARRAY IS SORTED!!
#Find the indexes where the value 7 should be inserted:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print("Posistion where 7 should be inserted:",x)
x = np.searchsorted(arr, 10)
print("Posistion where 10 should be inserted:",x)

#Search from the right side:
#Find the indexes where the value 7 should be inserted, starting from the right:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print("Position where 7 shoulde be inserted starting from the right:",x)

Where is 4: (array([3, 5, 6]),)
Posistion where 7 should be inserted: 1
Posistion where 10 should be inserted: 4
Position where 7 shoulde be inserted from the right: 2


In [73]:
"""NumPy Sorting Arrays: Returns a copy of the array!"""
#1-D sort()
arr = np.array([3, 2, 0, 1])
print("1-D Sort:",np.sort(arr))

#2-D sort()
arr = np.array([[3, 2, 4], [5, 0, 1]])
print("2-D Sort:\n",np.sort(arr))

1-D Sort: [0 1 2 3]
2-D Sort:
 [[2 3 4]
 [0 1 5]]


In [78]:
"""NumPy Filter Array: Getting some elements out of an existing array and creating a new array out of them is called filtering. In NumPy, you filter
an array using a boolean index list. A boolean index list is a list of booleans corresponding to indexes in the array.If the value at an index is True
that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array."""
#Ex 1:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

#Create a filter array that will return only values higher than 42
arr = np.array([41, 42, 43, 44])
filter_arr = []
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

#Simpler way to create a filter array that will return only values higher than 42
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

#filter for even elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[41 43]
[False, False, True, True]
[43 44]
[False False  True  True]
[43 44]
[False  True False  True False  True False]
[2 4 6]
